version: "3.9"
services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend.Dockerfile
    ports:
      - "3000:3000"   # use 3000:3000 if 3000 is free
    environment:
      NODE_ENV: production